### ISSUE TITLE
Why RedisClient is incomplete ?

### ISSUE THREAD

**Issue by Garfield028** [NServiceKit/NServiceKit.Redis#1]
hi,

I liked to use the "RemoveByPattern" method RedisClient class.
Unfortunately, it is not avaialble.
Do you intend to update the class soon?

Thank you.

**Comment by vdaron** [comment]
I just add the method RemoveByPattern

Let me know if it works as expected

V.

**Comment by Garfield028** [comment]
thank you,

I started on GitHub. I do not yet know very well the procedures.
Is it possible for you to publish the Nuget package?

thank you

**Comment by vdaron** [comment]
I'm not responsible of Nuget packages

This is a good opportunity to learn. (http://rogerdudler.github.io/git-guide/)

V.

**Comment by mirthy** [comment]
Building it now and pushing to the public Nuget when it's done

**Comment by mirthy** [comment]
Pushed to public nuget as NServiceKit.Redis.1.0.10
