### ISSUE TITLE
some problem  in  Get<T>(string key)

### ISSUE THREAD

**Issue by Liuqin** [NServiceKit/NServiceKit.Redis#12]
when we used the last vision,and  in .net 4.0 
there are some mistake in here
our log :
The offset and length went beyond the bounds of an array Or count is greater than the number of elements from index to source collection the end

```
System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
NServiceKit.Redis.RedisNativeClient.WriteToSendBuffer(Byte[] cmdBytes)
```

   NServiceKit.Redis.RedisNativeClient.WriteAllToSendBuffer(Byte[][] cmdWithBinaryArgs)
   NServiceKit.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   NServiceKit.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   NServiceKit.Redis.RedisClient.Get[T](String key)

**Comment by vdaron** [comment]
HI @Liuqin could you please give me a more complete example ti be able to reproduce the problem

Thanks

**Comment by Liuqin** [comment]
I am not sure about  what had happened !

the logs just console as  out of element index 

I redo the serisizeale in my way ,but the bug still happened !

I think maybe it cause by some dirty data in our database!

**Comment by Liuqin** [comment]
I am sorry ,I  used Singleton pattern in the project, so the objects hadn't been dispose
