### ISSUE TITLE
TypeLoadException ScanKeys

### ISSUE THREAD

**Issue by x0d3r** [NServiceKit/NServiceKit.Redis#5]
I Have this error:

``` csharp
Method 'ScanKeys' in type 'NServiceKit.Redis.RedisClient' from assembly 'NServiceKit.Redis, Version=1.0.14.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Any clue ??

**Comment by mirthy** [comment]
Taking a look at this, it should have an implementation.

**Comment by mirthy** [comment]
Got, it looks like the 1.0.14.0 got built with the wrong reference to the interface.  Fixing that now.

**Comment by mirthy** [comment]
OK, NServiceKit.Redis 1.0.16.0 should fix the issue, let me know if it hasn't fixed it for you.

**Comment by x0d3r** [comment]
Yep it's fixed now, thanks !!
