### ISSUE TITLE
ZADD with multiple values/scores

### ISSUE THREAD

**Issue by yurigorokhov** [NServiceKit/NServiceKit.Redis#7]
I propose exposing a method that allows a batch ZADD:

ZADD key score1 value1 score2 value2 score3 value3 ...

https://github.com/NServiceKit/NServiceKit.Redis/compare/master...yurigorokhov:master

Does this seem like a good API addition? If so I will make a pull request.

From my testing this method is much, much faster than the pipelined AddRangeToSortedSet command.

**Comment by vdaron** [comment]
Hi Yuri,

Send your pull request, I'll review it asap

Vincent.

**Comment by yurigorokhov** [comment]
@vdaron thanks!

Here we go!
https://github.com/NServiceKit/NServiceKit.Redis/pull/8
https://github.com/NServiceKit/NServiceKit/pull/39
